# Offense count: 7
RSpec/AnyInstance:
  Exclude:
    - 'spec/loadrunner/command_line_spec.rb'
    - 'spec/loadrunner/server_spec.rb'
    - 'spec/loadrunner/status_spec.rb'

# Offense count: 4
RSpec/StubbedMock:
  Exclude:
    - 'spec/loadrunner/command_line_spec.rb'
    - 'spec/loadrunner/status_spec.rb'
