# Offense count: 6
# This cop supports safe autocorrection (--autocorrect).
Performance/RegexpMatch:
  Exclude:
    - 'lib/loadrunner/client.rb'
    - 'lib/loadrunner/command_line.rb'
    - 'lib/loadrunner/server.rb'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
Performance/StringInclude:
  Exclude:
    - 'lib/loadrunner/server.rb'

# Offense count: 7
RSpec/AnyInstance:
  Exclude:
    - 'spec/loadrunner/command_line_spec.rb'
    - 'spec/loadrunner/server_spec.rb'
    - 'spec/loadrunner/status_spec.rb'

# Offense count: 2
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 10

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: CustomTransform, IgnoredWords, DisallowedExamples.
# DisallowedExamples: works
RSpec/ExampleWording:
  Exclude:
    - 'spec/loadrunner/server_spec.rb'

# Offense count: 4
RSpec/StubbedMock:
  Exclude:
    - 'spec/loadrunner/command_line_spec.rb'
    - 'spec/loadrunner/status_spec.rb'

# Offense count: 3
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, conditionals
Style/AndOr:
  Exclude:
    - 'lib/loadrunner/signature_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, ProceduralMethods, FunctionalMethods, AllowedMethods, AllowedPatterns, AllowBracesOnProceduralOneLiners, BracesRequiredMethods.
# SupportedStyles: line_count_based, semantic, braces_for_chaining, always_braces
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# AllowedMethods: lambda, proc, it
Style/BlockDelimiters:
  Exclude:
    - 'spec/loadrunner/github_api_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, SingleLineConditionsOnly, IncludeTernaryExpressions.
# SupportedStyles: assign_to_condition, assign_inside_condition
Style/ConditionalAssignment:
  Exclude:
    - 'lib/loadrunner/server.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/DefWithParentheses:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/ExpandPathArguments:
  Exclude:
    - 'loadrunner.gemspec'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Style/GlobalStdStream:
  Exclude:
    - 'bin/loadrunner'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: MinBodyLength, AllowConsecutiveConditionals.
Style/GuardClause:
  Exclude:
    - 'lib/loadrunner/command_line.rb'

# Offense count: 6
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, EnforcedShorthandSyntax, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
# SupportedShorthandSyntax: always, never, either, consistent
Style/HashSyntax:
  Exclude:
    - 'spec/loadrunner/client_spec.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Style/RedundantInterpolation:
  Exclude:
    - 'lib/loadrunner/runner.rb'

# Offense count: 3
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Exclude:
    - 'lib/loadrunner/runner.rb'
    - 'lib/loadrunner/signature_helper.rb'

# Offense count: 3
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'lib/loadrunner/client.rb'
    - 'lib/loadrunner/server.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/StderrPuts:
  Exclude:
    - 'bin/loadrunner'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: Mode.
Style/StringConcatenation:
  Exclude:
    - 'lib/loadrunner/client.rb'
    - 'lib/loadrunner/signature_helper.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, AllowedPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 126
