language: ruby

rvm:
  - "2.3.0"
  - "2.4.1"

notifications:
  email: false

before_install:
  - chmod -R +x spec/fixtures/handlers

script: bundle exec rspec

# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: [always|never|change] # default: change
#     on_failure: [always|never|change] # default: always

