#!/usr/bin/env ruby

puts "--------------------------------------------------"
puts "Push Hook called"
puts "This hook is called when pushing to master"

env_vars = [
  'LOADRUNNER_REPO', 'LOADRUNNER_OWNER',
  'LOADRUNNER_EVENT', 'LOADRUNNER_BRANCH',
  'LOADRUNNER_REF', 'LOADRUNNER_TAG', 'LOADRUNNER_COMMIT'
]

env_vars.each do |varname|
  puts "- #{varname}: #{ENV[varname]}"
end
