#!/usr/bin/env ruby

puts "--------------------------------------------------"
puts "Push Handler called"
puts "This handler is called when pushing to master"

env_vars = [
  'LOADRUNNER_REPO', 'LOADRUNNER_EVENT', 'LOADRUNNER_BRANCH', 
  'LOADRUNNER_REF', 'LOADRUNNER_TAG', 'LOADRUNNER_PAYLOAD'
]

env_vars.each do |varname|
  puts "- #{varname}: #{ENV[varname]}"
end
